import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useTheme} from 'next-themes'
import Myteam from '../components/Myteam'
import LeftNav from '../components/LeftNav'

const Home: NextPage = () => {
  const {theme, setTheme} = useTheme()

  return (
    <div className="min-h-full">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row bg-blue-800 dark:bg-gray-600 h-screen min-h-full ">
        <LeftNav/>
        <Myteam/>
      </div>
    </div>
  )
}

export default Home
