import type { NextPage } from 'next'
import Head from 'next/head'
import LeftNav from '../../components/LeftNav'
import TopHeader from '../../components/TopHeader'
import styles from '../../styles/Home.module.css'

const Dashboard: NextPage = () => {

  return (
    <div className="min-w-full">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row min-h-screen'>
        <div className='basis-1/5'>
        <LeftNav />
        </div>
        <div className="basis-4/5 bg-gray dark:bg-gray">
          <TopHeader/>
          <h1 className="text-2xl">Dashboard</h1>
          <div className='flex flex-row min-w-full'>
            <div className='basis-7/12 bg-gray-50  border mx-4 mb-2 rounded-md'>
              <div className='flex flex-row flex-wrap justify-around text-black p-5'>
                <div className='w-5/12'>
                  <div className='border bg-white px-5 py-3 '>
                    <h4 className='text-ms'>Total Income</h4>
                    <h2 className='text-lg text-blue-600 font-semibold'>612.785</h2>
                  </div>
                </div>
                <div className='w-5/12'>
                  <div className='border bg-white px-5 py-3 '>
                    <h4 className='text-ms'>Residual Income</h4>
                    <h2 className='text-lg text-blue-600 font-semibold'>10.785</h2>
                  </div>
                </div>
                <div className='w-11/12 bg-blue-500 rounded-md text-center text-white text-xs py-1 mt-5 '>Receive</div>

              </div>
            </div>
            <div className='basis-5/12  bg-gray-50 border mx-4 mb-2 rounded-md'>
              <div className='text-black p-2'>
                <div>Referal System :</div>
                <div>Earn 10% for direct refferals and 5% for indirect refferals</div>
              </div>
            </div>
          </div>
          <div className='align-middle text-left mx-4 '>
            <table className="min-w-full ">
              <thead>
                <tr className='border bg-white text-xs text-gray-900'>
                  <th className='px-6 py-3 w-2/5 '>ID Number</th>
                  <th className='px-6 py-3 w-2/5 '>Nickname</th>
                  <th className='px-6 py-3 w-1/5 '>Registration Time</th>
                </tr>
              </thead>
              <tbody className='bg-gray-50 text-xs text-gray-500'>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
                <tr>
                  <td className='px-6 py-3 '>092830</td>
                  <td className='px-6 py-3 '>Dave4Deni</td>
                  <td className='px-6 py-3 '>08-05-22  <span className='ml-10'>10:40</span></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;